version: "3.9"

services:
  dev: 
    image: dev:latest
    container_name: dev_container 
    stdin_open: true 
    tty: true 
    volumes: 
      - ./workspace:/root/workspace 
      - ./homefiles/.config/nvim/init.vim:/root/.config/nvim/init.vim
      - ./homefiles/.config/nvim/coc-settings.json:/root/.config/nvim/coc-settings.json
      - ./homefiles/.config/nvim/plugged/:/root/.config/nvim/plugged/ 
      - ./homefiles/.zshrc:/root/.zshrc  
      - ./homefiles/.gitconfig:/root/.gitconfig
