-- General
vim.g.mapleader = ","
vim.o.showmatch = true -- show the matching closing bracket
vim.o.hidden = true -- hide current unsaved file instead of closing it when opening a new file
vim.o.showcmd = true -- show partial command you type in the last line of the screen
vim.o.wildmenu = true -- enable auto completion menu after pressing TAB
vim.o.wildmode = "list:longest", "list:full" -- allow for completions similar to Bash
vim.o.lazyredraw = true -- the screen will not be redrawn while executing macros
vim.o.backupdir = "~/.cache/nvim/backups" -- directory to store backup files.
vim.o.ignorecase = true -- case insensitive
vim.o.hlsearch = true -- highlight search
vim.o.incsearch = true -- incremental search
vim.o.smartcase = true -- override the 'ignorecase' option if the search pattern contains upper case characters
vim.o.tabstop = 4 -- number of columns occupied by a tab
vim.o.softtabstop = 4 -- see multiple spaces as tabstops
vim.o.expandtab = true -- converts tabs to white space
vim.o.shiftwidth = 4 -- width for autoindents
vim.o.autoindent = true -- indent a new line the same amount as the line just typed
vim.o.number = true -- display current line number
vim.o.relativenumber = true -- display relative line numbers
vim.o.ruler = true -- display a visual ruler to see line width
vim.o.cc = 144 -- set a 144 column border for good coding style
vim.o.textwidth = 144 -- text width; move to start of file and fire gqG to re-format
vim.o.mouse = "a" -- enable mouse click
vim.o.cursorline = true -- highlight current cursorline
vim.o.ttyfast = true -- speed up scrolling in Vim
vim.o.mousemodel = "popup" -- right mouse opens a popup menu like Windows
vim.o.updatetime = 300 -- millisecs vim waits after you stop typing before it triggers plugins like git-gutter
vim.o.signcolumn = "yes" -- show the column where signs like git-gutter ones show up
vim.o.foldenable = false -- disable code folding to improve performance
